[tool.isort]
profile = "black"
line_length = 88

[tool.black]
line_length = 88

[tool.mypy]
python_version = "3.11"
warn_return_any = true
warn_unused_configs = true

[[tool.mypy.overrides]]
module = [
    "astropy.*",
    "galsim",
    "ngmix",
    "yaml",
]
ignore_missing_imports = true
