name: tests

on:
  push:
    branches:
      - main
  pull_request: null
  workflow_dispatch: null
  schedule:
    - cron: 0 23 * * 4  # Run tests at 11pm UTC every Thursday.

jobs:
  tests:
    name: tests
    strategy:
      matrix:
        pyver: ["3.11"]

    runs-on: "ubuntu-latest"

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v4

      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.pyver }}
          channels: conda-forge,defaults
          channel-priority: strict
          show-channel-urls: true
          miniforge-version: latest

      - name: Configure conda and install dependencies
        shell: bash -l {0}
        run: |
          conda config --set always_yes yes
          conda install -q stackvana=0

          pip install --no-deps git+https://github.com/LSSTDESC/descwl_coadd.git

      - name: Setup
        shell: bash -l {0}
        run: |
          setup -v -r .

      - name: Run tests
        shell: bash -l {0}
        run: |
          pytest -v descwl_coadd_task/tests/ --cov= --cov-report=xml --cov-report=term-missing

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage.xml
          fail_ci_if_error: false
          token: ${{ secrets.CODECOV_TOKEN }}
